### ISSUE TITLE
Keep getting a error, and commands not working on discord

### ISSUE THREAD

**Issue by PrintModuIe** [soakingdry/rodrobe#5]
Is there any fixes to this, if you can help me, or maybe message me on discord, I would really appreciate it.

![error1](https://github.com/soakingdry/rodrobe/assets/109107084/dc755f9a-4942-4e5d-b680-050944a715f4)
![error2](https://github.com/soakingdry/rodrobe/assets/109107084/5807d42e-57b6-44c3-9783-a6458be9d607)

**Comment by PrintModuIe** [comment]
if you wanted to message me on discord as I am more active on there it's, @vexiusz

**Comment by PrintModuIe** [comment]
Just fixed this issue, I forgot to change the discord id's

**Comment by soakingdry** [comment]
Ill push an update to get rid of that error message.

**Comment by PrintModuIe** [comment]
> Ill push an update to get rid of that error message.

do you possibly have discord I would like a few questions and need some help

**Comment by soakingdry** [comment]
> do you possibly have discord I would like a few questions and need some help

We can commute through https://discord.gg/rJxXUxAF
